---
title: "figure_DE_grass"
author: "Katja K"
date: "05/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r overall grass}

library(ggplot2)
library(pheatmap)
library(ggpubr)
library(dplyr)
library(tidyverse)
library(treemapify)

load("grass_de_new.RData")

ovr_nsig_data <- ovr_nsig_data %>%
  mutate(Main_test = ifelse(any(grepl("Straw-", test)), "Straw addition effect", "Time effect with straw addition"))

ovr_nsig_data$condition <- factor(ovr_nsig_data$condition, levels = c("Control", "Straw", "T1", "T3", "T6"))
ovr_nsig_data$test <- factor(ovr_nsig_data$test, levels = c("Straw-T1", "Straw-T3", "Straw-T6", "T3vT1-Straw", "T6vT1-Straw", "T6vT3-Straw"),  labels = c("T1", "T3", "T6", "T3vsT1", "T6vT1", "T6vT3"))
  
de_grass_overview <- ggplot(data = ovr_nsig_data) +
  geom_bar(aes(x = test, y = log10(num_sig), fill = condition),
           position = "dodge",stat = "identity") +
  geom_text(aes(test, log10(num_sig), label=num_sig, group = condition),
            vjust = 1.5, size=4, position = position_dodge(width = .9)) +
  facet_wrap(~Main_test, scales = "free_x") +
  scale_fill_manual(values = c("#F5B041", "#6C3483", "#D5D8DC", "#808B96", "#2C3E50")) +
  ylab("Number of DE transcripts [log10]") +
  theme_pubclean(base_size = 12) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.title.x = element_blank()) + labs(fill = "") + labs(tag="b)")

ggsave("figures/de_grass_overall.jpeg", width = 20, height = 15, units = "cm")

```