---
title: "DE_overall_analysis"
author: "Katja K"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(ggplot2)
library(pheatmap)
library(ggpubr)
library(dplyr)
library(tidyverse)
library(treemapify)
library(ggplotify)
````

# Overall DE
```{r load data}
load("overall_de1.RData")
```

## Effect of Straw in Wheat
```{r straw in wheat, message=FALSE, warning=FALSE}

ws_all_tdb <- ws_all %>% 
  filter(condition == "Straw") %>%
  group_by(enz_class, enz_family) %>%
  summarise(num_sig= n(), mean_log2FC = mean(abs(log2FoldChange))) %>%
  filter(!is.na(enz_class)) %>%
  arrange(desc(num_sig))

treemap_WS <- ggplot(data = ws_all_tdb, aes(fill = mean_log2FC, area = num_sig, label= enz_family, subgroup=enz_class)) +
  geom_treemap() +
  geom_treemap_text(colour ="white", place = "centre") +
  theme_pubclean(base_size = 12) +
  scale_fill_gradient(low = "#A9CCE3", high = "#1B4F72", limits = c(9, 30)) + labs(fill = "Mean log2 fold-change")
```

```{r ws counts, message=FALSE, warning=FALSE}

ws_all %>% 
  filter(condition == "Straw") %>%
  dim()
sum(ws_all_tdb$num_sig)
head(ws_all_tdb, 10)

```

## Effect of Straw in Grass

```{r straw in grass, message=FALSE, warning=FALSE}

gs_all_tdb <- gs_all %>% 
  filter(condition == "Straw") %>%
  group_by(enz_class, enz_family) %>%
  summarise(num_sig= n(), mean_log2FC = mean(abs(log2FoldChange))) %>%
  filter(!is.na(enz_class)) %>%
  arrange(desc(num_sig))

treemap_GS <- ggplot(data = gs_all_tdb, aes(fill = mean_log2FC, area = num_sig, label= enz_family, subgroup=enz_class)) +
  geom_treemap() +
  geom_treemap_text(colour ="white", place = "centre") +
  theme_pubclean(base_size = 12) +
  scale_fill_gradient(low = "#bde657", high = "#0b4c3f", limits = c(9, 30)) + labs(fill = "Mean log2 fold-change")
```

```{r gs counts, message=FALSE, warning=FALSE}

gs_all %>% 
  filter(condition == "Straw") %>%
  dim()
sum(gs_all_tdb$num_sig)
head(gs_all_tdb, 10)

```

# Effect of land-use
## Within control
### Wheat

```{r land use C wheat, message=FALSE, warning=FALSE}

lu_c_all_tdb <- lu_c_all %>% 
  filter(condition == "Wheat") %>%
  group_by(enz_class, enz_family) %>%
  summarise(num_sig= n(), mean_log2FC = mean(abs(log2FoldChange))) %>%
  filter(!is.na(enz_class)) %>%
  arrange(desc(num_sig))

treemap_W_C <- ggplot(data = lu_c_all_tdb, aes(fill = mean_log2FC, area = num_sig, label= enz_family, subgroup=enz_class)) +
  geom_treemap() +
  geom_treemap_text(colour ="white", place = "centre") +
  theme_pubclean(base_size = 12) +
  scale_fill_gradient(low = "#A9CCE3", high = "#1B4F72", limits = c(2,35)) + labs(fill = "Mean log2 fold-change")
```

```{r wheat lu count, message=FALSE, warning=FALSE}

lu_c_all %>% 
  filter(condition == "Wheat") %>%
  dim()
sum(ws_all_tdb$num_sig)
head(lu_c_all_tdb, 10)

```

### Grass

```{r land use C grass, message=FALSE, warning=FALSE}

lu_c_all_tdb <- lu_c_all %>% 
  filter(condition == "Grass") %>%
  group_by(enz_class, enz_family) %>%
  summarise(num_sig= n(), mean_log2FC = mean(abs(log2FoldChange))) %>%
  filter(!is.na(enz_class)) %>%
  arrange(desc(num_sig))

treemap_G_C <- ggplot(data = lu_c_all_tdb, aes(fill = mean_log2FC, area = num_sig, label= enz_family, subgroup=enz_class)) +
  geom_treemap() +
  geom_treemap_text(colour ="white", place = "centre") +
  theme_pubclean(base_size = 12) +
  scale_fill_gradient(low =  "#bde657", high = "#0b4c3f", limits = c(2,35)) + labs(fill = "Mean log2 fold-change")
```

```{r grass lu count, message=FALSE, warning=FALSE}

lu_c_all %>% 
 filter(condition == "Grass") %>%
  dim()
sum(gs_all_tdb$num_sig)
head(lu_c_all_tdb, 10)

```

### merge treemaps 

```{r merge treemaps, message=FALSE, warning=FALSE}

ggarrange(treemap_WS, treemap_GS, labels = c("a)", "b)"), nrow = 2)
ggsave("figures/Fig6.pdf", width = 25, height = 25, units = "cm")

```

#### Heatmap

```{r save pheatmap function, include=FALSE}

save_pheatmap_png <- function(x, filename, width=1200, height=1000, res = 150) {
  png(filename, width = width, height = height, res = res)
  grid::grid.newpage()
  grid::grid.draw(x$gtable)
  dev.off()
}

save_pheatmap_pdf <- function(x, filename, width=10, height=7) {
    stopifnot(!missing(x))
    stopifnot(!missing(filename))
    pdf(filename, width=width, height=height)
    grid::grid.newpage()
    grid::grid.draw(x$gtable)
    dev.off()
}
```

```{r heatmap wheat, message=FALSE, warning=FALSE}

tmm_mat <- read.table("SeqCap_filt_gene.TMM.EXPR.matrix", header = T, row.names = 1, check.names = F)
sample_meta <-  read.table("All.samples", header = T, check.names = F)
names(sample_meta)[names(sample_meta) == "Manag"] <- "Land-use"
names(sample_meta)[names(sample_meta) == "Time"] <- "Time point"
sm_c <- sample_meta %>% filter(Straw == "C")

rownames(sm_c) <- sm_c$sampleID

lu_c_egg <- lu_c_all %>% 
  filter(!is.na(cog_lev1))
lu_c_tmm_egg <- tmm_mat[lu_c_egg$Transcript, (colnames(tmm_mat) %in% sm_c$sampleID)]

lu_c_tmm_egg_cog_lev2 <- lu_c_tmm_egg %>%
  rownames_to_column(var = "Transcript") %>%
  gather(Sample_ID, count, -Transcript) %>% 
  left_join(lu_c_egg, by = "Transcript") %>% 
  group_by(Sample_ID, cog_lev2) %>%
  summarise(sum_count = sum(count)) %>%
  spread(Sample_ID, sum_count)
temp <- lu_c_tmm_egg_cog_lev2$cog_lev2
lu_c_tmm_egg_cog_lev2$cog_lev2 <- NULL
row.names(lu_c_tmm_egg_cog_lev2) <- temp

my_colour = list(
    `Land-use` = c(G = "#0e6251", W = "#2472a4"), 
    `Time point` = c(T1 = "#D5D8DC", T3 = "#808B96", T6 = "#2C3E50")
)

make_bold_names <- function(mat, rc_fun, rc_names) {
  bold_names <- rc_fun(mat)
  ids <- rc_names %>% match(rc_fun(mat))
  ids %>%
    walk(
      function(i)
        bold_names[i] <<-
        bquote(bold(.(rc_fun(mat)[i]))) %>%
        as.expression()
    )
  bold_names
}

sm_c <- sm_c[with(sm_c, order(`Land-use`, `Time point`)),]
lu_c_tmm_egg_cog_lev2 <- lu_c_tmm_egg_cog_lev2[sm_c$sampleID]
row.names(lu_c_tmm_egg_cog_lev2) <- temp

pheatmap_LU_C <- pheatmap(lu_c_tmm_egg_cog_lev2,  scale = "row", annotation_colors = my_colour, show_colnames = F, border_color=NA, annotation_col=sm_c[,c("Land-use", "Time point"),drop=F], labels_row = make_bold_names(lu_c_tmm_egg_cog_lev2, rownames, c("Carbohydrate transport and metabolism")),  col = colorRampPalette(c("navy", "white", "firebrick3"))(50), cluster_cols = F, fontsize=14)
print(pheatmap_LU_C)
```

```{r heatmap ID wheat, message=FALSE, warning=FALSE}

lu_c_tmm_egg_cog_enz <- lu_c_tmm_egg %>%
  rownames_to_column(var = "Transcript") %>%
  gather(Sample_ID, count, -Transcript) %>% 
  left_join(lu_c_egg, by = "Transcript") %>% 
  filter(cog_lev2 == "Carbohydrate transport and metabolism") %>%
  group_by(Sample_ID, cog_enzid) %>%
  summarise(sum_count = sum(count)) %>%
  spread(Sample_ID, sum_count)

temp <- lu_c_tmm_egg_cog_enz$cog_enzid
lu_c_tmm_egg_cog_enz$cog_enzid <- NULL
lu_c_tmm_egg_cog_enz <- as.data.frame(lu_c_tmm_egg_cog_enz)
row.names(lu_c_tmm_egg_cog_enz) <- temp

my_colour = list(
    `Land-use`  = c(G = "#7ca619", W = "#c4e1f5"),
   `Time point` = c(T1 = "#D5D8DC", T3 = "#808B96", T6 = "#2C3E50")
)

sm_c <- sm_c[with(sm_c, order(`Land-use`, `Time point`)),]
lu_c_tmm_egg_cog_enz <- lu_c_tmm_egg_cog_enz[sm_c$sampleID]
row.names(lu_c_tmm_egg_cog_enz) <- temp

pheatmap_LU_C_enzID <- pheatmap(lu_c_tmm_egg_cog_enz, border_color=NA, annotation_col=sm_c[,c("Land-use", "Time point"),drop=F],annotation_legend=T, scale = "row", annotation_colors = my_colour, show_colnames = F, cluster_cols =  F, col = colorRampPalette(c("navy", "white", "firebrick3"))(50),fontsize=14)
print(pheatmap_LU_C_enzID)
```

## Within straw
### Wheat

```{r land use S wheat, message=FALSE, warning=FALSE}

lu_s_all_tdb <- lu_s_all %>% 
  filter(condition == "Wheat") %>%
  group_by(enz_class, enz_family) %>%
  summarise(num_sig= n(), mean_log2FC = mean(abs(log2FoldChange))) %>%
  filter(!is.na(enz_class)) %>%
  arrange(desc(num_sig))

treemap_W_S <- ggplot(data = lu_s_all_tdb, aes(fill = mean_log2FC, area = num_sig, label= enz_family, subgroup=enz_class)) +
  geom_treemap() +
  geom_treemap_text(colour ="white", place = "centre") +
  theme_pubclean(base_size = 12) +
  scale_fill_gradient(low = "#A9CCE3", high = "#1B4F72", limits = c(2,35))  + labs(fill = "Mean log2 fold-change")
```

### Grass

```{r land use C straw, message=FALSE, warning=FALSE}

lu_s_all_tdb <- lu_s_all %>% 
  filter(condition == "Grass") %>%
  group_by(enz_class, enz_family) %>%
  summarise(num_sig= n(), mean_log2FC = mean(abs(log2FoldChange))) %>%
  filter(!is.na(enz_class)) %>%
  arrange(desc(num_sig))

treemap_G_S <- ggplot(data = lu_s_all_tdb, aes(fill = mean_log2FC, area = num_sig, label= enz_family, subgroup=enz_class)) +
  geom_treemap() +
  geom_treemap_text(colour ="white", place = "centre") +
  theme_pubclean(base_size = 12) +
  scale_fill_gradient(low =  "#A3E4D7", high = "#117864", limits = c(2,35)) + labs(fill = "Mean log2 fold-change")
```

### merge treemaps LU

```{r merge treemaps LU, message=FALSE, warning=FALSE}

ggarrange(treemap_W_C, treemap_G_C, treemap_W_S, treemap_G_S, labels = c("a)", "b)", "c)", "d)"), ncol = 2, nrow = 2)
ggsave("figures/FigS3.pdf", width = 35, height = 25, units = "cm")
```

#### Heatmap

```{r heatmap grass, message=FALSE, warning=FALSE}

tmm_mat <- read.table("SeqCap_filt_gene.TMM.EXPR.matrix", header = T, row.names = 1, check.names = F)
sample_meta <-  read.table("All.samples", header = T, check.names = F)
names(sample_meta)[names(sample_meta) == "Manag"] <- "Land-use"
names(sample_meta)[names(sample_meta) == "Time"] <- "Time point"
sm_c <- sample_meta %>% filter(Straw == "S")
rownames(sm_c) <- sm_c$sampleID

lu_s_egg <- lu_s_all %>% 
  filter(!is.na(cog_lev1))
lu_s_tmm_egg <- tmm_mat[lu_s_egg$Transcript, (colnames(tmm_mat) %in% sm_c$sampleID)]

lu_s_tmm_egg_cog_lev2 <- lu_s_tmm_egg %>%
  rownames_to_column(var = "Transcript") %>%
  gather(Sample_ID, count, -Transcript) %>% 
  left_join(lu_s_egg, by = "Transcript") %>% 
  group_by(Sample_ID, cog_lev2) %>%
  summarise(sum_count = sum(count)) %>%
  spread(Sample_ID, sum_count)
temp <- lu_s_tmm_egg_cog_lev2$cog_lev2
lu_s_tmm_egg_cog_lev2$cog_lev2 <- NULL
row.names(lu_s_tmm_egg_cog_lev2) <- temp

my_colour = list(
    `Land-use` = c(G = "#0e6251", W = "#2472a4"), 
    `Time point` = c(T1 = "#D5D8DC", T3 = "#808B96", T6 = "#2C3E50")
)

sm_c <- sm_c[with(sm_c, order(`Land-use`, `Time point`)),]
lu_s_tmm_egg_cog_lev2 <- lu_s_tmm_egg_cog_lev2[sm_c$sampleID]
row.names(lu_s_tmm_egg_cog_lev2) <- temp

pheatmap_LU_S <- pheatmap(lu_s_tmm_egg_cog_lev2, border_color=NA, annotation_col=sm_c[,c("Land-use", "Time point"),drop=F],annotation_legend=T, scale = "row", annotation_colors = my_colour, show_colnames = F, labels_row = make_bold_names(lu_s_tmm_egg_cog_lev2, rownames, c("Carbohydrate transport and metabolism")),  cluster_cols =  F, col = colorRampPalette(c("navy", "white", "firebrick3"))(50), fontsize = 14)
```

```{r heatmap ID grass, message=FALSE, warning=FALSE}

lu_s_tmm_egg_cog_enz <- lu_s_tmm_egg %>%
  rownames_to_column(var = "Transcript") %>%
  gather(Sample_ID, count, -Transcript) %>% 
  left_join(lu_s_egg, by = "Transcript") %>% 
  filter(cog_lev2 == "Carbohydrate transport and metabolism") %>%
  group_by(Sample_ID, cog_enzid) %>%
  summarise(sum_count = sum(count)) %>%
  spread(Sample_ID, sum_count)

temp <- lu_s_tmm_egg_cog_enz$cog_enzid
lu_s_tmm_egg_cog_enz$cog_enzid <- NULL
row.names(lu_s_tmm_egg_cog_enz) <- temp

my_colour = list(
    `Land-use` = c(G = "#0e6251", W = "#2472a4"), 
    `Time point` = c(T1 = "#D5D8DC", T3 = "#808B96", T6 = "#2C3E50")
)

sm_c <- sm_c[with(sm_c, order(`Land-use`, `Time point`)),]
lu_s_tmm_egg_cog_enz <- lu_s_tmm_egg_cog_enz[sm_c$sampleID]
row.names(lu_s_tmm_egg_cog_enz) <- temp

pheatmap_LU_S_enzID <- pheatmap(lu_s_tmm_egg_cog_enz, border_color=NA, annotation_col=sm_c[,c("Land-use", "Time point"),drop=F],annotation_legend=T, scale = "row", annotation_colors = my_colour, cluster_cols = F, show_colnames = F,col = colorRampPalette(c("navy", "white", "firebrick3"))(50), fontsize = 14)
```

### merge heatmap

```{r merge heatmap, message=FALSE, warning=FALSE}

p1 <- as.ggplot(pheatmap_LU_C)
p2 <- as.ggplot(pheatmap_LU_S)
p3 <- as.ggplot(pheatmap_LU_C_enzID)
p4 <- as.ggplot(pheatmap_LU_S_enzID)

ggarrange(p1, p2, p3, p4, labels = c("a)", "b)", "c)", "d)"), ncol = 2, nrow = 2, common.legend = T, legend="right")
ggsave("figures/heatmaps_LU_all.pdf", width = 55, height = 33, units = "cm", dpi=500)

ggarrange(p3, p4, labels = c("a)", "b)"), ncol = 2, nrow = 1, common.legend = T, legend="right")
ggsave("figures/Fig5.pdf", width = 60, height = 25, units = "cm", dpi=500)
```

