---
title: "Taxonomy after rRNA removal step"
author: "Katja K"
date: "28/06/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(cowplot)
library(tidyverse)
library(ggplot2)
library(phyloseq)
library(ggpubr)
```
*This script is for the taxonomy, after rRNA removal*

# Data

```{r upload and prepare data, message=FALSE, warning=FALSE}
load("overall_de1.RData")
physeq_tax <- readRDS("physeq_tax.RDS")
silva_hits <- read.table("Trinity_ass_200_vs_Sil132DB_all_NEW.hits")
```

```{r bacteria, message=FALSE, warning=FALSE}
tdb_annot_new <- tdb_annot %>% rownames_to_column("OTU") 
badTaxa = silva_hits %>% filter(!(V1 %in% tdb_annot_new$OTU))
allTaxa = taxa_names(physeq_tax)
allTaxa <- allTaxa[!(allTaxa %in% badTaxa$V1)]
taxa_all_new = prune_taxa(allTaxa, physeq_tax) %>% transform_sample_counts(function(x) {x/sum(x)})

taxa_Bacteria_new <- subset_taxa(taxa_all_new, !Kingdom %in% c ("unknown", "Viruses", "Archaea","Eukaryota"))
taxa_Eukaryota_new <- subset_taxa(taxa_all_new, !Kingdom %in% c ("unknown", "Viruses", "Archaea","Bacteria"))
taxa_Archaea_new <- subset_taxa(taxa_all_new, !Kingdom %in% c ("unknown", "Viruses", "Eukaryota","Bacteria"))

top_5phyla <- sort(tapply(taxa_sums(taxa_Bacteria_new), tax_table(taxa_Bacteria_new)[, "Phylum"], sum), decreasing=TRUE)[1:5]
top_bact_5phyla <- subset_taxa(taxa_Bacteria_new, Phylum %in% names(top_5phyla))

top_bact_5phyla <- top_bact_5phyla %>%
  tax_glom(taxrank = "Phylum") %>%                      # agglomerate
  psmelt() %>%                                          # Melt to long format
  arrange(Phylum)  

top_bact_5phyla_percent <- top_bact_5phyla
top_bact_5phyla_percent$Abundance <- top_bact_5phyla$Abundance/4 #because we have 4 samples per land-use:treatment and TPM values

#top_bact_5phyla_percent <- top_bact_5phyla_percent %>% 
#  left_join(tdb_annot %>% rownames_to_column("OTU"), by = "OTU") %>%top_5phyla
#  filter(!(is.na(enz_class)) & (OTU %in% silva_hits$V1)) 

top_bact_5phyla_percent$Phylum <- factor(top_bact_5phyla_percent$Phylum, levels = c("Acidobacteria", "Actinobacteria", "Chloroflexi", "Proteobacteria", "unknown.Bacteria"), labels = c("Acidobacteria", "Actinobacteria", "Chloroflexi", "Proteobacteria", "Unknown"))

top_bact_5phyla <- ggplot(top_bact_5phyla_percent, aes(Manag.Straw, Abundance, fill = Phylum)) +
  geom_col(show.legend = TRUE) + facet_wrap(~Time) + scale_y_continuous(labels = scales::percent) + scale_fill_manual(values=c("#0652b6", "#939d05", "#b60652", "#06aab6", "#b66a06")) + xlab("Land-use + amendment") + ylab("Abundance [%]") + theme_bw() + theme(axis.text = element_text(size = 12), panel.grid = element_blank()) +
  theme(axis.title = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12)) + 
  theme(legend.text = element_text(size = 12)) + 
  theme(strip.text.x = element_text(size = 12)) + theme(axis.title.x = element_blank(),axis.text.x = element_blank(), axis.ticks.x = element_blank())
```

```{r eukaryota, message=FALSE, warning=FALSE}

top_5phyla_euk <- sort(tapply(taxa_sums(taxa_Eukaryota_new), tax_table(taxa_Eukaryota_new)[, "Phylum"], sum), decreasing=TRUE)[1:5]
top_euk_5phyla <- subset_taxa(taxa_Eukaryota_new, Phylum %in% names(top_5phyla_euk))

top_euk_5phyla <- top_euk_5phyla %>%
  tax_glom(taxrank = "Phylum") %>%                      # agglomerate
  psmelt() %>%                                          # Melt to long format
  arrange(Phylum)  

top_euk_5phyla_percent <- top_euk_5phyla
top_euk_5phyla_percent$Abundance <- top_euk_5phyla$Abundance/4 #because we have 4 samples per land-use:treatment and TPM values

top_euk_5phyla_percent$Phylum <- factor(top_euk_5phyla_percent$Phylum, levels = c("Arthropoda","Ascomycota","Nematoda","Streptophyta","unknown.Eukaryota"), labels = c("Arthropoda","Ascomycota","Nematoda","Streptophyta","Unknown"))

top_euk_5phyla <- ggplot(top_euk_5phyla_percent, aes(Manag.Straw, Abundance, fill = Phylum)) +
  geom_col(show.legend = TRUE) + facet_wrap(~Time) + scale_y_continuous(labels = scales::percent) + scale_fill_manual(values=c("#0652b6", "#939d05", "#b60652", "#06aab6", "#b66a06")) + xlab("Land-use + amendment") + ylab("Abundance [%]") + theme_bw() + theme(axis.text = element_text(size = 12), panel.grid = element_blank()) + 
  theme(axis.title = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12)) + 
  theme(legend.text = element_text(size = 12)) + 
  theme(strip.text.x = element_text(size = 12)) + theme(axis.title.x = element_blank(),axis.text.x = element_blank(), axis.ticks.x = element_blank())

```

```{r archaea, message=FALSE, warning=FALSE}

top_5phyla_arch <- sort(tapply(taxa_sums(taxa_Archaea_new), tax_table(taxa_Archaea_new)[, "Phylum"], sum), decreasing=TRUE)[1:5]
top_arch_5phyla <- subset_taxa(taxa_Archaea_new, Phylum %in% names(top_5phyla_arch))

top_arch_5phyla <- top_arch_5phyla %>%
  tax_glom(taxrank = "Phylum") %>%                      # agglomerate
  psmelt() %>%                                          # Melt to long format
  arrange(Phylum)  

top_arch_5phyla_percent <- top_arch_5phyla
top_arch_5phyla_percent$Abundance <- top_arch_5phyla$Abundance/4 #because we have 4 samples per land-use:treatment and TPM values

top_arch_5phyla_percent$Phylum <- factor(top_arch_5phyla_percent$Phylum, levels = c("Candidatus Bathyarchaeota","Crenarchaeota","Euryarchaeota","Thaumarchaeota","unknown.Archaea"), labels = c("Candidatus Bathyarchaeota","Crenarchaeota","Euryarchaeota","Thaumarchaeota","Unknown"))

top_arch_5phyla <- ggplot(top_arch_5phyla_percent, aes(Manag.Straw, Abundance, fill = Phylum)) +
  geom_col(show.legend = TRUE) + facet_wrap(~Time) + scale_y_continuous(labels = scales::percent) + scale_fill_manual(values=c("#0652b6", "#939d05", "#b60652", "#06aab6", "#b66a06")) + xlab("Land-use + amendment") + ylab("Abundance [%]") + theme_bw() + theme(axis.text = element_text(size = 12), panel.grid = element_blank()) +
  theme(axis.title = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12)) + 
  theme(legend.text = element_text(size = 12)) + 
  theme(strip.text.x = element_text(size = 12)) 

```

```{r merge, message=FALSE, warning=FALSE}

plot_grid(top_bact_5phyla + theme(legend.justification = "left"), top_euk_5phyla + theme(legend.justification = "left"), top_arch_5phyla +theme(legend.justification = "left"), labels = c("a)", "b)", "c)"), ncol = 1, align = "hv")
ggsave("figures/top_phyla_all_NEW.pdf", width = 25, height = 25, units = "cm")

```

# DE taxonomy

```{r de taxonomy, message=FALSE, warning=FALSE}
ws_all_taxa <- ws_all_annot %>%
   filter(!(is.na(enz_class) & (Transcript %in% silva_hits$V1))) %>% 
  group_by(Kingdom, Phylum, direction, condition) %>%
  filter(!is.na(Phylum)) %>%
  summarise(num_sig= n())
ws_all_taxa$soil <- "Wheat"

gs_all_taxa <- gs_all_annot %>%
  filter(!(is.na(enz_class) & (Transcript %in% silva_hits$V1))) %>% 
  group_by(Kingdom, Phylum, direction, condition) %>%
  filter(!is.na(Phylum)) %>%
  summarise(num_sig= n())
gs_all_taxa$soil <- "Grass"

taxa_both <- rbind(ws_all_taxa, gs_all_taxa)
taxa_both$lu_con <- paste(taxa_both$soil, taxa_both$condition, sep = "_")

rem_phyla <- taxa_both %>% 
  group_by(Phylum) %>%
  summarise(tot_sig= sum(num_sig)) %>%
  filter(tot_sig > 4)

taxa_both <- taxa_both %>% 
  filter(Phylum %in% rem_phyla$Phylum) %>%
  select(Kingdom, Phylum, direction, lu_con, num_sig)

test <- taxa_both %>% 
  unite(x, c(Kingdom, Phylum), sep = "-") %>%
  unite(y, c(direction, lu_con), sep = "-")
test$x <- factor(test$x)
test$y <- factor(test$y)
test <- complete(test, x, y, fill = list(num_sig = NA))

taxa_both_final <- test %>% 
  separate(x, c("Kingdom", "Phylum"), sep = "-") %>%
  separate(y, c("direction", "lu_con"), sep = "-")

taxa_both_final$Kingdom <- factor(taxa_both_final$Kingdom, levels = c("Bacteria", "Eukaryota", "unknown"), labels = c("Bacteria", "Eukaryota", "Unknown"))
taxa_both_final$lu_con <- factor(taxa_both_final$lu_con, levels = c("Grass_Control", "Wheat_Control", "Grass_Straw", "Wheat_Straw"), labels = c("GC", "WC", "GS", "WS"))
taxa_both_final$Phylum <- factor(taxa_both_final$Phylum, levels = c("Acidobacteria", "Actinobacteria", "Ascomycota", "Bacteroidetes", "Chloroflexi", "Firmicutes", "Proteobacteria", "Streptophyta", "unknown.Bacteria", "unknown.Eukaryota", "unknown"), labels =c("Acidobacteria", "Actinobacteria", "Ascomycota", "Bacteroidetes", "Chloroflexi", "Firmicutes", "Proteobacteria", "Streptophyta", "unknown", "unknown", "unknown"))
taxa_both_final$direction <- factor(taxa_both_final$direction)

ggplot() + 
  geom_bar(data = subset(taxa_both_final, direction == "Positive"), 
           aes(x = Phylum, y = num_sig, fill = lu_con), stat = "identity", position = position_dodge(preserve = "single")) +
  geom_bar(data = subset(taxa_both_final, direction == "Negative"), 
           aes(x = Phylum, y = -num_sig, fill = lu_con), stat = "identity", position = position_dodge(preserve = "single")) +
  geom_hline(yintercept = 0,colour = "grey90") + 
  geom_text(data = subset(taxa_both_final, direction == "Positive"), 
            aes(Phylum, num_sig, label=num_sig, group = lu_con), 
            vjust = -0.5, size=4, position = position_dodge(width = .9)) +
  geom_text(data = subset(taxa_both_final, direction == "Negative"), 
      aes(Phylum, -num_sig, label=num_sig, group = lu_con), 
      vjust = 1.5, size=4, position = position_dodge(width = .9)) +
  theme_light(base_size = 10) +
  ylab("Number of DE transcripts") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), panel.grid.major.y = element_blank(), panel.grid.minor = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(), legend.title = element_blank()) +
  facet_grid(cols = vars(Kingdom), space = "free", scales = "free") +
  scale_fill_manual(values = c("#A3E4D7", "#1ABC9C", "#AED6F1", "#2980B9")) + theme(axis.text = element_text(size = 12)) + 
  theme(axis.title = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12)) + 
  theme(legend.text = element_text(size = 12)) + 
  theme(strip.text.x = element_text(size = 12)) + labs(fill="Land-use + amendment")

ggsave("figures/taxa_straw_add.pdf", width = 25, height = 15, units = "cm")

```

## Important phyla

```{r}

ws_all_taxa <- ws_all_annot %>%
  filter(!(is.na(enz_class) & (Transcript %in% silva_hits$V1))) %>% 
  group_by(Phylum, Genus, direction, condition) %>%
  filter(!is.na(Genus)) %>%
  summarise(num_sig= n())

```

```{r}

ws_all_taxa$soil <- "Wheat"

gs_all_taxa <- gs_all_annot %>%
  filter(!(is.na(enz_class) & (Transcript %in% silva_hits$V1))) %>% 
  group_by(Phylum, Genus, direction, condition) %>%
  filter(!is.na(Genus)) %>%
  summarise(num_sig= n())

```

```{r}

gs_all_taxa$soil <- "Grass"

taxa_both <- rbind(ws_all_taxa, gs_all_taxa)
taxa_both$lu_con <- paste(taxa_both$soil, taxa_both$condition, sep = "_")

keep_phyla <- c("Actinobacteria", "Proteobacteria", "Ascomycota")

rem_phyla <- taxa_both %>% 
  filter(Phylum %in% keep_phyla) %>%
  group_by(Genus) %>%
  summarise(tot_sig= sum(num_sig)) %>%
  filter(tot_sig > 4)

taxa_both <- taxa_both %>% 
  filter(Phylum %in% keep_phyla) %>%
  filter(Genus %in% rem_phyla$Genus) %>%
  select(Phylum, Genus, direction, lu_con, num_sig)

test <- taxa_both %>% 
  unite(x, c(Phylum, Genus), sep = "-") %>%
  unite(y, c(direction, lu_con), sep = "-")
test$x <- factor(test$x)
test$y <- factor(test$y)
test <- complete(test, x, y, fill = list(num_sig = NA))

taxa_both_final <- test %>% 
  separate(x, c("Phylum", "Genus"), sep = "-") %>%
  separate(y, c("direction", "lu_con"), sep = "-") %>%
  filter(Phylum %in% keep_phyla)

taxa_both_final$Phylum <- factor(taxa_both_final$Phylum, levels = c("Actinobacteria", "Proteobacteria", "Ascomycota"))
taxa_both_final$lu_con <- factor(taxa_both_final$lu_con, levels = c("Grass_Control", "Wheat_Control", "Grass_Straw", "Wheat_Straw"), labels = c("GC", "WC", "GS", "WS"))
taxa_both_final$Genus <- factor(taxa_both_final$Genus)
taxa_both_final$direction <- factor(taxa_both_final$direction)

ggplot() + 
  geom_bar(data = subset(taxa_both_final, direction == "Positive"), 
           aes(x = Genus, y = num_sig, fill = lu_con), stat = "identity", position = position_dodge(preserve = "single")) +
  geom_bar(data = subset(taxa_both_final, direction == "Negative"), 
           aes(x = Genus, y = -num_sig, fill = lu_con), stat = "identity", position = position_dodge(preserve = "single")) +
  geom_hline(yintercept = 0, colour = "grey90") + 
  geom_text(data = subset(taxa_both_final, direction == "Positive"), 
            aes(Genus, num_sig, label=num_sig, group = lu_con), 
            vjust = -0.5, size=4, position = position_dodge(width = .9)) +
  geom_text(data = subset(taxa_both_final, direction == "Negative"), 
      aes(Genus, -num_sig, label=num_sig, group = lu_con), 
      vjust = 1.5, size=4, position = position_dodge(width = .9)) +
  theme_light(base_size = 12) +
  ylab("Number of DE transcripts") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), panel.grid.major.y = element_blank(), panel.grid.minor = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(), legend.title = element_blank()) +
  facet_grid(cols = vars(Phylum), space = "free", scales = "free") +
  scale_fill_manual(values = c("#A3E4D7", "#1ABC9C", "#AED6F1", "#2980B9")) + theme(axis.text = element_text(size = 12)) + 
  theme(axis.title = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12)) + 
  theme(legend.text = element_text(size = 12)) + 
  theme(strip.text.x = element_text(size = 12)) + labs(fill="Land-use + amendment")

ggsave("figures/bact_genus_plot.pdf", width = 26, height = 17, units = "cm")

```