---
title: "Taxonomic annotations"
author: "Katja K"
date: "28/06/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(cowplot)
library(tidyverse)
library(ggplot2)
library(phyloseq)
library(ggpubr)
```
*This script is for the taxonomy, after rRNA removal*

# Overall taxonomy
```{r upload and prepare data, message=FALSE, warning=FALSE}
load("overall_de1.RData")
physeq_tax <- readRDS("physeq_tax.RDS")
silva_hits <- read.table("Trinity_ass_200_vs_Sil132DB_all_NEW.hits")
```
## Bacteria
```{r bacteria, message=FALSE, warning=FALSE}
tdb_annot_new <- tdb_annot %>% rownames_to_column("OTU") 
badTaxa = silva_hits %>% filter(!(V1 %in% tdb_annot_new$OTU))
allTaxa = taxa_names(physeq_tax)
allTaxa <- allTaxa[!(allTaxa %in% badTaxa$V1)]
taxa_all_new = prune_taxa(allTaxa, physeq_tax) %>% transform_sample_counts(function(x) {x/sum(x)})

taxa_Bacteria_new <- subset_taxa(taxa_all_new, !Kingdom %in% c ("unknown", "Viruses", "Archaea","Eukaryota"))
taxa_Eukaryota_new <- subset_taxa(taxa_all_new, !Kingdom %in% c ("unknown", "Viruses", "Archaea","Bacteria"))
taxa_Archaea_new <- subset_taxa(taxa_all_new, !Kingdom %in% c ("unknown", "Viruses", "Eukaryota","Bacteria"))

top_5phyla <- sort(tapply(taxa_sums(taxa_Bacteria_new), tax_table(taxa_Bacteria_new)[, "Phylum"], sum), decreasing=TRUE)[1:5]
top_bact_5phyla <- subset_taxa(taxa_Bacteria_new, Phylum %in% names(top_5phyla))

top_bact_5phyla <- top_bact_5phyla %>%
  tax_glom(taxrank = "Phylum") %>%                      # agglomerate
  psmelt() %>%                                          # Melt to long format
  arrange(Phylum)  

top_bact_5phyla_percent <- top_bact_5phyla
top_bact_5phyla_percent$Abundance <- top_bact_5phyla$Abundance/4 #because we have 4 samples per land-use:treatment and TPM values

top_bact_5phyla_percent$Phylum <- factor(top_bact_5phyla_percent$Phylum, levels = c("Acidobacteria", "Actinobacteria", "Chloroflexi", "Proteobacteria", "unknown.Bacteria"), labels = c("Acidobacteria", "Actinobacteria", "Chloroflexi", "Proteobacteria", "Unknown"))

top_bact_5phyla <- ggplot(top_bact_5phyla_percent, aes(Manag.Straw, Abundance, fill = Phylum)) +
  geom_col(show.legend = TRUE) + facet_wrap(~Time) + scale_y_continuous(labels = scales::percent) + scale_fill_manual(values=c("#0652b6", "#939d05", "#b60652", "#06aab6", "#b66a06")) + xlab("Land-use + amendment") + ylab("Abundance [%]") + theme_bw() + theme(axis.text = element_text(size = 12), panel.grid = element_blank()) +
  theme(axis.title = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12)) + 
  theme(legend.text = element_text(size = 12)) + 
  theme(strip.text.x = element_text(size = 12)) + theme(axis.title.x = element_blank(),axis.text.x = element_blank(), axis.ticks.x = element_blank())
```
## Eukaryota
```{r eukaryota, message=FALSE, warning=FALSE}

top_5phyla_euk <- sort(tapply(taxa_sums(taxa_Eukaryota_new), tax_table(taxa_Eukaryota_new)[, "Phylum"], sum), decreasing=TRUE)[1:5]
top_euk_5phyla <- subset_taxa(taxa_Eukaryota_new, Phylum %in% names(top_5phyla_euk))

top_euk_5phyla <- top_euk_5phyla %>%
  tax_glom(taxrank = "Phylum") %>%                      # agglomerate
  psmelt() %>%                                          # Melt to long format
  arrange(Phylum)  

top_euk_5phyla_percent <- top_euk_5phyla
top_euk_5phyla_percent$Abundance <- top_euk_5phyla$Abundance/4 #because we have 4 samples per land-use:treatment and TPM values

top_euk_5phyla_percent$Phylum <- factor(top_euk_5phyla_percent$Phylum, levels = c("Arthropoda","Ascomycota","Nematoda","Streptophyta","unknown.Eukaryota"), labels = c("Arthropoda","Ascomycota","Nematoda","Streptophyta","Unknown"))

top_euk_5phyla <- ggplot(top_euk_5phyla_percent, aes(Manag.Straw, Abundance, fill = Phylum)) +
  geom_col(show.legend = TRUE) + facet_wrap(~Time) + scale_y_continuous(labels = scales::percent) + scale_fill_manual(values=c("#0652b6", "#939d05", "#b60652", "#06aab6", "#b66a06")) + xlab("Land-use + amendment") + ylab("Abundance [%]") + theme_bw() + theme(axis.text = element_text(size = 12), panel.grid = element_blank()) + 
  theme(axis.title = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12)) + 
  theme(legend.text = element_text(size = 12)) + 
  theme(strip.text.x = element_text(size = 12)) + theme(axis.title.x = element_blank(),axis.text.x = element_blank(), axis.ticks.x = element_blank())
```
## Archaea
```{r archaea, message=FALSE, warning=FALSE}

top_5phyla_arch <- sort(tapply(taxa_sums(taxa_Archaea_new), tax_table(taxa_Archaea_new)[, "Phylum"], sum), decreasing=TRUE)[1:5]
top_arch_5phyla <- subset_taxa(taxa_Archaea_new, Phylum %in% names(top_5phyla_arch))

top_arch_5phyla <- top_arch_5phyla %>%
  tax_glom(taxrank = "Phylum") %>%                      # agglomerate
  psmelt() %>%                                          # Melt to long format
  arrange(Phylum)  

top_arch_5phyla_percent <- top_arch_5phyla
top_arch_5phyla_percent$Abundance <- top_arch_5phyla$Abundance/4 #because we have 4 samples per land-use:treatment and TPM values

top_arch_5phyla_percent$Phylum <- factor(top_arch_5phyla_percent$Phylum, levels = c("Candidatus Bathyarchaeota","Crenarchaeota","Euryarchaeota","Thaumarchaeota","unknown.Archaea"), labels = c("Candidatus Bathyarchaeota","Crenarchaeota","Euryarchaeota","Thaumarchaeota","Unknown"))

top_arch_5phyla <- ggplot(top_arch_5phyla_percent, aes(Manag.Straw, Abundance, fill = Phylum)) +
  geom_col(show.legend = TRUE) + facet_wrap(~Time) + scale_y_continuous(labels = scales::percent) + scale_fill_manual(values=c("#0652b6", "#939d05", "#b60652", "#06aab6", "#b66a06")) + xlab("Land-use + amendment") + ylab("Abundance [%]") + theme_bw() + theme(axis.text = element_text(size = 12), panel.grid = element_blank()) +
  theme(axis.title = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12)) + 
  theme(legend.text = element_text(size = 12)) + 
  theme(strip.text.x = element_text(size = 12)) 
```
### Merge 
```{r merge, message=FALSE, warning=FALSE}

plot_grid(top_bact_5phyla + theme(legend.justification = "left"), top_euk_5phyla + theme(legend.justification = "left"), top_arch_5phyla +theme(legend.justification = "left"), labels = c("a)", "b)", "c)"), ncol = 1, align = "hv")
ggsave("figures/FigS2.pdf", width = 25, height = 25, units = "cm")
```
